
server.port=8082
spring.application.name=ms-producto

spring.datasource.url=jdbc:oracle:thin:@y9yihlwya0utl6x4_medium?TNS_ADMIN=/Users/danielguzman/Desktop/Hospital_VM/Wallet_Y9YIHLWYA0UTL6X4
spring.datasource.username=ADMIN
spring.datasource.password=FullStack-001
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1