# Puerto en el que corre la Bodega
server.port=8083

# Configuración de la conexión a Oracle Cloud (Usa tus mismos datos de ms-producto)
spring.datasource.url=jdbc:oracle:thin:@y9yihlwya0utl6x4_medium?TNS_ADMIN=/Users/danielguzman/Desktop/Hospital_VM/Wallet_Y9YIHLWYA0UTL6X4
spring.datasource.username=ADMIN
spring.datasource.password=FullStack-001
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# URL ENLAZADA: Ruta para que WebClient localice al catálogo de productos
app.urls.ms-producto=http://localhost:8082